### PR TITLE
ARMv5TE (DS) support

### PR DESCRIPTION
**Pull request by AetiasHax**
I've added support for ARMv5TE, used by the main ARM9 processor of the DS. [The disassembler library](https://github.com/AetiasHax/unarm) can be extended to support other ARM versions, and I have plans to add ARMv4T for GBA soon, followed by ARMv6 for the 3DS.

There's currently no version detection in place. [This document from ARM](https://github.com/ARM-software/abi-aa/blob/main/aaelf32/aaelf32.rst#build-attributes) does specify where version information should be stored (see `Tag_CPU_name`), but in my experience working with the DS toolchain, I found no such information. Would a dropdown in the "Arch Settings" window be acceptable?

### CODE REVIEW

**Comment by encounter** [comment]
Thanks for the PR! Looks good at an initial glance, but I’d like to revert the unnecessary README changes, especially the changes around to config file example, since that’s not valid JSON. 🙂

**Comment by encounter** [comment]
> Would a dropdown in the "Arch Settings" window be acceptable?

Yes, this seems like a good solution, though auto-detection would be nice eventually (if possible). It could be similar to the MIPS settings, where it has an “Auto” option, but can be set manually.

**Comment by AetiasHax** [comment]
> Thanks for the PR! Looks good at an initial glance, but I’d like to revert the unnecessary README changes, especially the changes to config file example, since that’s not valid JSON. 🙂

That's weird, I don't know how that commit happened. Fixing!

**Comment by AetiasHax** [comment]
> > Would a dropdown in the "Arch Settings" window be acceptable?
> 
> Yes, this seems like a good solution, though auto-detection would be nice eventually (if possible). It could be similar to the MIPS settings, where it has an “Auto” option, but can be set manually.

In that case, I could implement auto-detection in a non-standard way for the "Auto" option. Possibly by looking at the compiler name/version, or something of the sort.

**Pull request merged**
